FROM ubuntu:24.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    make \
    libgtest-dev \
    ca-certificates \
 && cd /usr/src/googletest \
 && cmake -S . -B build \
 && cmake --build build \
 && cmake --install build \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /src
