FROM emscripten/emsdk:3.1.71

WORKDIR /src

CMD ["em++", "-std=c++17", "-O3", "-Icpp-logic/include", "--preload-file", "cpp-logic/data/wordlists/answerList.txt", "--preload-file", "cpp-logic/data/wordlists/guessList.txt", "cpp-logic/src/wasm_exports.cpp", "cpp-logic/src/engine.cpp", "-o", "frontend/wordle.js", "-s", "WASM=1", "-s", "EXPORTED_FUNCTIONS=[\"_createNewGame\",\"_makeGuess\",\"_validateGuess\",\"_makeHardModeGuess\",\"_freeCString\",\"_free\",\"_malloc\"]", "-s", "EXPORTED_RUNTIME_METHODS=[\"ccall\",\"cwrap\",\"UTF8ToString\",\"stringToUTF8\",\"setValue\"]"]
