FROM emscripten/emsdk:3.1.71

WORKDIR /src

CMD ["em++", "-std=c++17", "-O3", "--preload-file", "wordLists/answerlist.txt", "--preload-file", "wordLists/guesslist.txt", "wordle.cpp", "-o", "wordle.js", "-s", "WASM=1", "-s", "EXPORTED_FUNCTIONS=[\"_getAnswerList\",\"_getGuessList\",\"_createNewGame\",\"_makeGuess\",\"_evaluateGuess\",\"_validateGuess\",\"_isMatch\",\"_filterAnswerList\",\"_findWorstFeedback\",\"_makeHardModeGuess\",\"_free\",\"_malloc\"]", "-s", "EXPORTED_RUNTIME_METHODS=[\"ccall\",\"cwrap\",\"UTF8ToString\",\"stringToUTF8\",\"setValue\"]"]
